---
- name: Add brew tap
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
  become: no

- name: Install fonts
  community.general.homebrew_cask:
    name: "{{ item }}"
  become: no
  loop:
    - font-hack-nerd-font
